### ISSUE TITLE
Testing Google Pay

### ISSUE THREAD

**Issue by carstenhag** [datatrans/android-sample-app#7]
Hello! I am trying out this sample, but unfortunately the Google Pay payment method never shows up.

I submit the test data including "PAY" as payment method, but then it doesn't show up in the list of payment methods.

**Comment by carstenhag** [comment]
So I adapted the sample to include this code in the `startTransaction(TransactionDetails transactionDetails, PaymentMethod scannedCard)` method.

```java
PaymentMethod googlePaymentMethod = PaymentMethod.createMethod(PaymentMethodType.GOOGLE_PAY);
PaymentProcessAndroid ppa = new PaymentProcessAndroid(dc, payment, googlePaymentMethod);
ppa.getPaymentOptions().setSkipAuthorizationCompletion(true);

ArrayList<PaymentMethodType> supportedNetworks = new ArrayList<>();
supportedNetworks.add(PaymentMethodType.MASTERCARD);
supportedNetworks.add(PaymentMethodType.VISA);
GooglePayConfig googlePayConfig = new GooglePayConfig(supportedNetworks, "Example Pay Config");
ppa.getPaymentOptions().setGooglePayConfig(googlePayConfig);
```

On the "New transaction" screen I fill in the test data. So far so good.  
Now, when specifying a payment method (PAY) and choosing redirect mode, the app crashes, due to the following error:

```
2019-07-04 14:16:30.145 30964-30964/ch.datatrans.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.datatrans.android.sample, PID: 30964
    java.lang.IllegalArgumentException: Google Pay payments have to be configured via the PaymentOptions.
        at ch.datatrans.payment.f.a(f.java:223)
        at ch.datatrans.payment.f.f(f.java:226)
        at ch.datatrans.payment.f.d(f.java:405)
        at ch.datatrans.payment.android.PaymentProcessAndroid.start(PaymentProcessAndroid.java:20)
        at ch.datatrans.android.sample.activities.TransactionActivity.startTransaction(TransactionActivity.java:268)
        at ch.datatrans.android.sample.activities.TransactionActivity.startTransaction(TransactionActivity.java:180)
        at ch.datatrans.android.sample.activities.TransactionActivity.access$100(TransactionActivity.java:46)
        at ch.datatrans.android.sample.activities.TransactionActivity$1.onSelection(TransactionActivity.java:94)
        at com.afollestad.materialdialogs.MaterialDialog.sendSingleChoiceCallback(MaterialDialog.java:310)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:338)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Not specifying the payment method seems to work, as it opens the payment sheet.  

Now it lets me select the google account and a credit card. When pressing "continue" it just says transaction completed though. There was no mention of any price or basket contents at any time, which confuses me. How can I specify that?

**Comment by fgrDtrx** [comment]
Hi @carstenhag I am looking into the issues you are having. Just to exclude this from the beginning since i do not see it in your code snippet but are you adding the GooglePay config by calling:

`ppa.getPaymentOptions().setGooglePayConfig(googlePayConfig);` ?

**Comment by carstenhag** [comment]
@fgrDtrx Hey! Oh sorry, the code was cut off. I've edited it in now. I did call the `setGooglePayConfig` method.

**Comment by fgrDtrx** [comment]
@carstenhag so I was able to reproduce your issue by calling `ppa.start()` before calling `  ppa.getPaymentOptions().setGooglePayConfig(googlePayConfig);` could it be that this is your issue? You should set the options before starting the payment process.  

Regarding the payment sheet not displaying the price or basket this is normal behaviour. It is slightly different than on the Web. Have a look at https://developers.google.com/pay/api/android/guides/brand-guidelines there you also see that the price and basket are not displayed in the payment sheet but beforehand.

**Comment by carstenhag** [comment]
Sorry for answering late.

After debugging a bit, this piece of code re-initializes ppa. Commenting it out, it works. I don't know why it was there though.

```
        if (transactionDetails.getPaymentMethod() != null && !transactionDetails.getPaymentMethod().isEmpty()) {
            try {
                PaymentMethodType paymentMethodType = PaymentMethodType.getPaymentMethodTypeByIdentifier(transactionDetails.getPaymentMethod());
                PaymentMethod paymentMethod = new PaymentMethod(paymentMethodType);
                ppa = new PaymentProcessAndroid(dc, payment, paymentMethod);
            } catch (IllegalArgumentException e) {
                // do nothing - just proceed with empty payment method
                Log.e("DatatransTest", e.getLocalizedMessage());
            }
        }
```

**Comment by fgrDtrx** [comment]
Hi @carstenhag 

this code is there to start the PaymentProcess with only the selected payment method when you fill it in the sample app gui.
